#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: calibrating the blind labeller (ADR-0007, issue #9).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRITERION="$REPO/docs/engineering-role-criterion.md"
WORK_DIR="${CORPUS_DIR:-$HOME/oneprofile-corpus}/calibration"
ANSWERS="$WORK_DIR/answers.tsv"
ITEMS="$WORK_DIR/items.tsv"
THRESHOLD=95

mkdir -p "$WORK_DIR"

# The criterion version a label was produced under, so a fixture can be read against the rules
# that were in force when it was made. The blob hash changes whenever the document does, which is
# also when ADR-0007 requires calibration to be re-run.
criterion_version() { git -C "$REPO" hash-object "$CRITERION" | cut -c1-12; }

# The 50 adversarial items, shuffled once so the strata are not walkable, and fixed here so the
# order is the same on every re-run. Each row is: index, title, verdict, source.
#
# The verdicts are NOT judgement calls. A `table` row is transcribed from the ruling table in the
# criterion; a `pair` row differs from a table row by exactly one feature of the three word lists,
# and its verdict follows from the procedure mechanically — a software qualifier suppresses Q0, an
# off-domain marker with no qualifier decides OUT, and `manager`, `designer` and `consultant` are
# deliberately not ambiguous words, so they fall through to the membership test and default to OUT.
# Any pair whose verdict could not be derived that way was dropped rather than guessed.
#
# Reading the verdicts before you label defeats the whole exercise: what is being measured is
# whether the criterion can be followed, not whether you can recall its answers.
write_items() {
	cat >"$ITEMS" <<'ITEMS_TSV'
1	graphic designer	OUT	pair
2	data scientist	IN	table
3	scrum master	IN	table
4	business analyst	UNKNOWN	table
5	field engineer	UNKNOWN	table
6	audit analyst	OUT	pair
7	civil engineer	OUT	table
8	network engineer	IN	table
9	implementation engineer	IN	table
10	payroll analyst	OUT	pair
11	research scientist	UNKNOWN	table
12	management consultant	OUT	pair
13	manufacturing systems engineer	IN	pair
14	solution engineer	IN	table
15	cloud architect	IN	pair
16	product manager	OUT	table
17	maintenance technician	OUT	pair
18	customer engineer	IN	table
19	embedded systems engineer	IN	pair
20	petroleum engineer	OUT	pair
21	solutions architect	IN	table
22	security analyst	IN	pair
23	aerospace engineer	OUT	pair
24	engineer ii	UNKNOWN	pair
25	technician	UNKNOWN	pair
26	systems administrator	IN	table
27	engineering manager	UNKNOWN	table
28	marketing analyst	UNKNOWN	pair
29	support engineer	UNKNOWN	table
30	hvac technician	OUT	pair
31	industrial engineer	UNKNOWN	pair
32	analyst	UNKNOWN	pair
33	data analyst	UNKNOWN	table
34	technical writer	UNKNOWN	table
35	architect	UNKNOWN	pair
36	sales engineer	UNKNOWN	table
37	technical program manager	IN	table
38	pharmacy technician	OUT	pair
39	mechanical software engineer	IN	pair
40	game designer	OUT	table
41	biomedical engineer	UNKNOWN	pair
42	agricultural engineer	OUT	pair
43	marketing manager	OUT	pair
44	database administrator	IN	table
45	mechanical engineer	OUT	table
46	electrical engineer	UNKNOWN	table
47	ux engineer	IN	table
48	game programmer	IN	table
49	software developer	IN	pair
50	embedded software engineer	IN	pair
ITEMS_TSV
}

banner "Calibrating the engineering-role labeller"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Read the criterion"
write_items
say "ADR-0007 requires the labeller to be calibrated before any round of #10 runs:"
say "50 adversarial titles, labelled by hand, checked against the ruling table."
printf '\n'
step "Open docs/engineering-role-criterion.md and read The procedure and The three lists."
warn "Do NOT read the Rulings table at the bottom. It holds the answers you are about to be scored against."
printf '\n'
note "What is being measured is whether the criterion is written clearly enough to follow."
note "A disagreement is evidence the document is ambiguous, not that you were careless:"
note "below ${THRESHOLD}% the criterion gets rewritten, and your labels stand."
printf '\n'
say "The 50 items are adversarial, meaning chosen to sit on the decision boundary —"
say "the phrases the ruling table fixes, each paired with a near-miss that differs by"
say "exactly one feature of the word lists. None of them is an obvious case."
printf '\n'
note "items:     $ITEMS"
note "criterion: version $(criterion_version)"
pause "Press Enter once you have read the procedure."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Label the 50 titles"
say "For each title, run the procedure top to bottom and answer:"
printf '\n'
step "${BOLD}i${RESET} — IN, it is an engineering role"
step "${BOLD}o${RESET} — OUT, and the title says so"
step "${BOLD}u${RESET} — UNKNOWN, the title does not carry enough to decide"
printf '\n'
note "UNKNOWN asks for a reason: d = domain_ambiguity, s = scope_ambiguity."
note "Every answer is written to disk as you give it, so Ctrl-C and re-run resumes here."
printf '\n'

touch "$ANSWERS"
answered=$(wc -l <"$ANSWERS")
if (( answered > 0 )); then
	note "resuming: $answered of 50 already answered"
	printf '\n'
fi

exec 3<"$ITEMS"
while IFS=$'\t' read -r index title verdict source <&3; do
	(( index <= answered )) && continue
	printf '\n  %s[%2s/50]%s  %s%s%s\n' "$DIM" "$index" "$RESET" "$BOLD" "$title" "$RESET"
	label=""
	while [[ -z "$label" ]]; do
		printf '    %si%s n / %so%s ut / %su%s nknown: ' "$BOLD" "$RESET" "$BOLD" "$RESET" "$BOLD" "$RESET"
		read -r answer <&0 || true
		case "$answer" in
			i|I) label="IN" ;;
			o|O) label="OUT" ;;
			u|U) label="UNKNOWN" ;;
			*) warn "answer i, o or u" ;;
		esac
	done
	reason=""
	if [[ "$label" == "UNKNOWN" ]]; then
		while [[ -z "$reason" ]]; do
			printf '    %sd%s omain / %ss%s cope ambiguity: ' "$BOLD" "$RESET" "$BOLD" "$RESET"
			read -r answer <&0 || true
			case "$answer" in
				d|D) reason="domain_ambiguity" ;;
				s|S) reason="scope_ambiguity" ;;
				*) warn "answer d or s" ;;
			esac
		done
	fi
	printf '%s\t%s\t%s\t%s\n' "$index" "$title" "$label" "$reason" >>"$ANSWERS"
done
exec 3<&-

printf '\n'
say "All 50 labelled."
pause "Press Enter to score them against the ruling table."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Score against the criterion"
say "Your labels, rejoined with the verdicts the criterion fixes."
printf '\n'

agreed=0
disagreed=0
while IFS=$'\t' read -r index title verdict source; do
	mine=$(awk -F'\t' -v i="$index" '$1 == i { print $3 }' "$ANSWERS")
	if [[ "$mine" == "$verdict" ]]; then
		agreed=$((agreed + 1))
	else
		disagreed=$((disagreed + 1))
		printf '  %s✗%s %-32s you said %-8s criterion says %-8s %s(%s)%s\n' \
			"$RED" "$RESET" "$title" "$mine" "$verdict" "$DIM" "$source" "$RESET"
	fi
done <"$ITEMS"

(( disagreed == 0 )) && say "No disagreements."
agreement=$(( agreed * 100 / 50 ))
printf '\n  %s%sAgreement: %s%% (%s of 50)%s\n\n' "$BOLD" "$BLUE" "$agreement" "$agreed" "$RESET"

note "Scored on the label alone. The ruling table does not fix a reason for every row, so"
note "domain_ambiguity vs scope_ambiguity is recorded in the fixture but not counted here."
printf '\n'

if (( agreement >= THRESHOLD )); then
	printf '  %s✓ At or above the %s%% gate. Rounds of #10 may run.%s\n' "$GREEN" "$THRESHOLD" "$RESET"
else
	printf '  %s⚠ Below the %s%% gate.%s\n' "$YELLOW" "$THRESHOLD" "$RESET"
	say "Per ADR-0007 the criterion is not written clearly enough to be followed."
	say "Each disagreement above points at the sentence to fix. Rewrite the criterion,"
	say "then re-run this wizard — a changed criterion requires re-calibration anyway."
fi
printf '\n'
pause "Press Enter to write the fixture."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Commit the fixture"
version="$(criterion_version)"
fixture="$REPO/src/test/resources/calibration/engineering-role-$(date +%Y-%m-%d).tsv"
mkdir -p "$(dirname "$fixture")"

if [[ -e "$fixture" ]]; then
	warn "$(basename "$fixture") already exists."
	say "Fixtures accumulate and are never replaced or regenerated (ADR-0007): a label set is a"
	say "statement about one sitting, and a session-driven labeller is not reproducible."
	if ! confirm "Write to a suffixed name instead?"; then
		say "Nothing written. Your answers are still at $ANSWERS"
		finish
		exit 0
	fi
	fixture="${fixture%.tsv}-$(date +%H%M).tsv"
fi

{
	printf '# Calibration set for the engineering-role labeller (issue #9, ADR-0007).\n'
	printf '# Labelled by hand on %s against criterion version %s.\n' "$(date +%Y-%m-%d)" "$version"
	printf '# Agreement with the ruling table: %s%% (%s of 50).\n' "$agreement" "$agreed"
	printf '# Held out of every measurement sample: a round never draws a title listed here.\n'
	printf '# title\tlabel\treason\tcriterion_verdict\tsource\n'
	while IFS=$'\t' read -r index title verdict source; do
		mine=$(awk -F'\t' -v i="$index" '$1 == i { print $3 }' "$ANSWERS")
		reason=$(awk -F'\t' -v i="$index" '$1 == i { print $4 }' "$ANSWERS")
		printf '%s\t%s\t%s\t%s\t%s\n' "$title" "$mine" "$reason" "$verdict" "$source"
	done <"$ITEMS"
} >"$fixture"

printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "${fixture#"$REPO"/}"
printf '\n'
say "Two things left, and both are yours — this wizard commits nothing:"
step "git add ${fixture#"$REPO"/} && commit it"
if (( agreement >= THRESHOLD )); then
	step "run /implement #10 for the first round"
else
	step "rewrite the criterion where the disagreements point, then re-run this wizard"
fi

finish
