#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: labelling a fresh boundary item set against the rewritten criterion.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRITERION="$REPO/docs/engineering-role-criterion.md"
WORK_DIR="${CORPUS_DIR:-$HOME/oneprofile-corpus}/calibration"
ANSWERS="$WORK_DIR/boundary-answers.tsv"
ITEMS="$WORK_DIR/boundary-items.tsv"

mkdir -p "$WORK_DIR"

criterion_version() { git -C "$REPO" hash-object "$CRITERION" | cut -c1-12; }

# Fifty boundary titles, every one of them a cleaned title that occurs in the corpus, picked by a
# session that had never seen a label or a verdict. They are NOT the 2026-09-20 fifty and none of
# those fifty appears here: that set is held out, and its answers were read by the session that
# rewrote the criterion, so re-running on it measures the fit rather than the document.
#
# There are no verdicts in this file, and that is the point. The rewritten criterion has never been
# scored against titles it was not fitted to, and nothing yet computes what its six steps return —
# the head is not stored and the classifier does not exist. So this script collects labels only.
#
# The items are not a random draw. Most corpus titles are easy; the criterion has failed twice at
# the boundary, so each row sits on one. The fourth column says which decision it probes:
#
#   absent-head     a common trailing word the head list does not carry, `specialist` above all
#   domain-attr     the same modifier under a domain-bound head and under a domain-free one
#   marker-clash    an off-domain marker and a software qualifier in the same title
#   two-heads       more than one head named, where "the first is the head" has to be applied
#   incapable-head  a software qualifier under a head that is not engineering-capable
#   never-head      a never-engineering head with a technical modifier
#   bare-head       a head with no qualifier and no marker at all
#
# Shuffled once so the strata are not walkable, and fixed here so the order is the same on a re-run.
write_items() {
	cat >"$ITEMS" <<'ITEMS_TSV'
1	sales specialist	specialist	absent-head	14
2	autonomous vehicle test driver	driver	never-head	3
3	engineer	engineer	bare-head	77
4	it specialist	specialist	absent-head	12
5	field engineer technician hourly	engineer	two-heads	11
6	marketing data analyst	analyst	domain-attr	4
7	quality assurance technician	technician	incapable-head	6
8	project civil engineer project manager	engineer	two-heads	25
9	security guard	guard	absent-head	3
10	engineering manager data platform	manager	two-heads	5
11	designer	designer	bare-head	48
12	product owner	owner	absent-head	21
13	security officer	officer	absent-head	56
14	engineering technician	technician	incapable-head	22
15	quality assurance specialist	specialist	absent-head	13
16	data strategist	strategist	absent-head	8
17	maintenance engineer	engineer	marker-clash	15
18	software engineering manager	manager	two-heads	21
19	business analyst consultant	analyst	two-heads	4
20	solutions consultant	consultant	incapable-head	46
21	data scientist manager	scientist	two-heads	4
22	financial systems analyst	analyst	domain-attr	6
23	data consultant	consultant	incapable-head	12
24	data manager	manager	incapable-head	4
25	clinical data scientist	scientist	domain-attr	3
26	generative ai associate flexible hours	associate	absent-head	61
27	technical recruiter	recruiter	absent-head	81
28	control systems technician	technician	marker-clash	3
29	director of engineering	director	absent-head	22
30	technical support representative	representative	never-head	7
31	web designer	designer	incapable-head	4
32	developer relations engineer	developer	two-heads	5
33	it support specialist	specialist	absent-head	34
34	healthcare solutions manager	manager	incapable-head	5
35	electro mechanical technician	technician	marker-clash	5
36	technical account manager	manager	incapable-head	87
37	marketing data scientist	scientist	domain-attr	4
38	technical trainer	trainer	never-head	3
39	developer	developer	bare-head	7
40	construction application analyst	analyst	domain-attr	6
41	manufacturing systems analyst	analyst	domain-attr	1
42	scientist	scientist	bare-head	10
43	manufacturing test engineer	engineer	marker-clash	8
44	graphics programmer	programmer	marker-clash	6
45	ux researcher	researcher	absent-head	16
46	consultant	consultant	bare-head	53
47	implementation specialist	specialist	absent-head	21
48	technical lead	lead	absent-head	8
49	security specialist	specialist	absent-head	34
50	business systems analyst	analyst	domain-attr	13
ITEMS_TSV
}

banner "Labelling the boundary item set"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Read the criterion"
write_items
say "Fifty boundary titles, none of them obvious, all of them real corpus titles."
printf '\n'
step "Open docs/engineering-role-criterion.md and read all of it, rulings table included."
printf '\n'
note "Read it the way the labeller does: the whole document, the rulings table included,"
note "and nothing else. What is being measured is whether it is written clearly enough to"
note "follow, so a disagreement is evidence about the document and not about you."
printf '\n'
say "Where these fifty came from, and why they are not the calibration set:"
printf '\n'
note "The 2026-09-20 fifty are held out. The session that rewrote the criterion had read"
note "their answers, so scoring against them measures the fit and not the document."
note "These fifty were picked by a session that had seen no label and no verdict, from the"
note "corpus, weighted toward the heads and modifier combinations the four lists do not"
note "obviously commit on. Frequencies run from 1 to 87 occurrences."
printf '\n'
note "items:     $ITEMS"
note "criterion: version $(criterion_version)"
pause "Press Enter once you have read the procedure."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Label the 50 titles"
say "For each title, run the six steps top to bottom and answer what they return:"
printf '\n'
step "${BOLD}i${RESET} — IN, it is an engineering role"
step "${BOLD}o${RESET} — OUT, and the title says so"
step "${BOLD}u${RESET} — UNKNOWN, the title does not carry enough to decide"
printf '\n'
note "UNKNOWN asks for a reason: r = unruled, d = domain_ambiguity, s = scope_ambiguity."
note "Answering unknown is not free. Which of the three it is matters as much as the label:"
note "unruled is our backlog, the other two are the corpus's."
note "Every answer is written to disk as you give it, so Ctrl-C and re-run resumes here."
printf '\n'

touch "$ANSWERS"
answered=$(wc -l <"$ANSWERS")
if (( answered > 0 )); then
	note "resuming: $answered of 50 already answered"
	printf '\n'
fi

exec 3<"$ITEMS"
while IFS=$'\t' read -r index title head probe n <&3; do
	(( index <= answered )) && continue
	printf '\n  %s[%2s/50]%s  %s%s%s\n' "$DIM" "$index" "$RESET" "$BOLD" "$title" "$RESET"
	label=""
	while [[ -z "$label" ]]; do
		printf '    %si%s n / %so%s ut / %su%s nknown: ' "$BOLD" "$RESET" "$BOLD" "$RESET" "$BOLD" "$RESET"
		read -r answer <&0 || true
		case "$answer" in
			i|I) label="IN" ;;
			o|O) label="OUT" ;;
			u|U) label="UNKNOWN" ;;
			*) warn "answer i, o or u" ;;
		esac
	done
	reason=""
	if [[ "$label" == "UNKNOWN" ]]; then
		while [[ -z "$reason" ]]; do
			printf '    %sr%s unruled / %sd%s omain / %ss%s cope: ' "$BOLD" "$RESET" "$BOLD" "$RESET" "$BOLD" "$RESET"
			read -r answer <&0 || true
			case "$answer" in
				r|R) reason="unruled" ;;
				d|D) reason="domain_ambiguity" ;;
				s|S) reason="scope_ambiguity" ;;
				*) warn "answer r, d or s" ;;
			esac
		done
	fi
	printf '%s\t%s\t%s\t%s\n' "$index" "$title" "$label" "$reason" >>"$ANSWERS"
done
exec 3<&-

printf '\n'
say "All 50 labelled."
pause "Press Enter to see what you said."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "What the labels came to"
say "There is nothing to score them against yet: the six steps are not computed anywhere,"
say "so this stage counts what you said and groups it by what each item probes."
printf '\n'

for state in IN OUT UNKNOWN; do
	count=$(awk -F'\t' -v s="$state" '$3 == s' "$ANSWERS" | wc -l)
	printf '  %s%-8s%s %s\n' "$BOLD" "$state" "$RESET" "$count"
done
printf '\n'
for reason in unruled domain_ambiguity scope_ambiguity; do
	count=$(awk -F'\t' -v r="$reason" '$4 == r' "$ANSWERS" | wc -l)
	printf '  %s  %-18s%s %s\n' "$DIM" "$reason" "$RESET" "$count"
done
printf '\n'

say "By what the item probes:"
printf '\n'
for probe in absent-head domain-attr marker-clash two-heads incapable-head never-head bare-head; do
	line=""
	while IFS=$'\t' read -r index title head p n; do
		[[ "$p" == "$probe" ]] || continue
		mine=$(awk -F'\t' -v i="$index" '$1 == i { print $3 }' "$ANSWERS")
		case "$mine" in IN) line+="I" ;; OUT) line+="O" ;; UNKNOWN) line+="u" ;; *) line+="." ;; esac
	done <"$ITEMS"
	printf '  %-16s %s\n' "$probe" "$line"
done
printf '\n'
note "I = IN, O = OUT, u = UNKNOWN. A probe that came out all u is a part of the criterion"
note "that reaches nothing; a probe that came out mixed is where the document is ambiguous."
printf '\n'
pause "Press Enter to write the fixture."

fixture="$REPO/src/test/resources/calibration/engineering-role-boundary-$(date +%Y-%m-%d).tsv"
mkdir -p "$(dirname "$fixture")"
if [[ -e "$fixture" ]]; then
	warn "$(basename "$fixture") already exists."
	say "Fixtures accumulate and are never replaced or regenerated (ADR-0007)."
	if ! confirm "Write to a suffixed name instead?"; then
		say "Nothing written. Your answers are still at $ANSWERS"
		finish
		exit 0
	fi
	fixture="${fixture%.tsv}-$(date +%H%M).tsv"
fi

{
	printf '# Boundary item set for the engineering-role criterion (issue #9, ADR-0007, ADR-0009).\n'
	printf '# Fifty corpus titles picked on the decision boundary by a session that had seen no label.\n'
	printf '# Labelled by hand on %s against criterion version %s.\n' "$(date +%Y-%m-%d)" "$(criterion_version)"
	printf '# Disjoint from engineering-role-2026-09-20.tsv, which stays held out of every sample.\n'
	printf '# No criterion verdict column: nothing computes the six steps yet.\n'
	printf '# title\tlabel\treason\thead\tprobe\tn\n'
	while IFS=$'\t' read -r index title head probe n; do
		mine=$(awk -F'\t' -v i="$index" '$1 == i { print $3 }' "$ANSWERS")
		reason=$(awk -F'\t' -v i="$index" '$1 == i { print $4 }' "$ANSWERS")
		printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$title" "$mine" "$reason" "$head" "$probe" "$n"
	done <"$ITEMS"
} >"$fixture"

printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "${fixture#"$REPO"/}"
printf '\n'
say "Yours from here — this script commits nothing:"
step "git add ${fixture#"$REPO"/} && commit it"
step "the labels are the answer key the criterion gets scored against once it can be computed"

finish
